1.	Obtener el nombre y el correo de todos los usuarios

In [25]:
import pandas as pd

df = pd.read_csv("./docsEj/datos_usuarios.csv",encoding="latin1")

df[["name","email"]]

                    name                        email
0         Katherine Reed         dvazquez@example.net
1         Madison Garcia      davidcarlos@example.com
2    Steven Gonzales PhD         lindamay@example.org
3         Cameron Little    osbornejoseph@example.net
4     Mrs. Sara Chambers        jeffrey29@example.org
..                   ...                          ...
496        Amber Simpson  kristinecamacho@example.com
497        Jon Wilkinson          tyler60@example.net
498       Matthew Watson        kenneth42@example.net
499      Amber Hernandez     jonesmatthew@example.org
500      Encarna Delgado            encarna@gmail.com

[501 rows x 2 columns]

2.	Obtener el nombre de todos los usuarios cuyo género es Femenino.

In [20]:
df[df["gender"] == "Femenino"]["name"]

6      Patricia Mullins
8       Richard Woodard
9        Deanna Daniels
10          Sarah Combs
13      Marissa Houston
             ...
488    Bridget Santiago
490        Nicole Nixon
491      Chase Thompson
494       Craig Collins
495        Alison Allen
Name: name, Length: 182, dtype: object

3.	Obtener el nombre de todos los usuarios cuyo sexo es Masculino y tengan una edad mayor a 50.

In [29]:
df[(df["gender"] == "Masculino") & (df["age"] > 50)]["name"]

0            Katherine Reed
1            Madison Garcia
3            Cameron Little
5             Ryan Mccarthy
7          Mr. Craig Martin
               ...
447         Michael Collins
467            Randy Wilson
479    Mr. Frederick Massey
492          Joshua Elliott
493          Andrew Edwards
Name: name, Length: 65, dtype: object

4.	Obtener todos los usuarios cuya edad sea mayor a 20

In [30]:
df[df["age"] > 20]

,username,email,name,gender,age,country,postcode
0,hlester,dvazquez@example.net,Katherine Reed,Masculino,58,Serbia,51235
1,amata,davidcarlos@example.com,Madison Garcia,Masculino,70,Aruba,23135
2,julianedwards,lindamay@example.org,Steven Gonzales PhD,No binario,68,Jamaica,12950
3,michael43,osbornejoseph@example.net,Cameron Little,Masculino,52,Cuba,47637
4,thompsonvalerie,jeffrey29@example.org,Mrs. Sara Chambers,No binario,36,Chile,78964
...,...,...,...,...,...,...,...
495,hdixon,qwhite@example.org,Alison Allen,Femenino,29,Afghanistan,48516
497,stewartkimberly,tyler60@example.net,Jon Wilkinson,No binario,49,Slovenia,58373
498,davisjennifer,kenneth42@example.net,Matthew Watson,No binario,42,Guam,21063
499,sharon40,jonesmatthew@example.org,Amber Hernandez,No binario,56,Ecuador,82104
500,edelgadoh,encarna@gmail.com,Encarna Delgado,masculino,45,España,19200

5.	Obtener el username y correo electrónico de los usuarios cuya edad se encuentre en el rango 50 a 60.

In [33]:
df[(df["age"] > 50) & (df["age"] < 60)][["username", "age"]]

          username  age
0          hlester   58
3        michael43   52
5    millerstephen   51
16     pamelaperry   54
26   joshuakennedy   56
..             ...  ...
476  morrisrichard   57
484   weberdiamond   58
485        qfields   58
487      stonelisa   52
499       sharon40   56

[80 rows x 2 columns]

6.	Obtener el username de todos los usuarios cuyo correo empiece con “e”

In [36]:
df[df["username"].str.startswith("e")]

,username,email,name,gender,age,country,postcode
28,evelyn62,nancywright@example.net,Anthony Whitaker DDS,No binario,27,Moldova,94674
31,eric67,nicholasrocha@example.net,Marcus Scott,Femenino,67,Croatia,1644
42,ehernandez,sean18@example.com,Patricia Morris,No binario,43,Saint Kitts and Nevis,50097
88,ebrooks,deborah86@example.org,Jay Holmes,Masculino,25,Rwanda,37135
115,esteele,dawn57@example.com,Victor Carlson,Femenino,33,Netherlands Antilles,74470
145,elizabeth79,lindagolden@example.com,Blake Morales,No binario,67,Switzerland,20878
163,erin32,dchavez@example.org,Steven Miranda,No binario,43,Macao,70113
184,emmawalker,jillcastillo@example.org,Lisa Bailey,No binario,20,Vietnam,58466
206,ebooker,nolanmark@example.org,Joshua Riddle,Masculino,76,Bhutan,54582
336,erikajohnson,bernarderic@example.net,Julia Thomas,Masculino,60,Finland,95909
377,estone,icabrera@example.net,Paul Garrett,No binario,46,Hong Kong,85101
441,eking,amandahanson@example.com,James Howe,Femenino,56,San Marino,75254
478,emyers,brandyprice@example.net,Emily Patton,No binario,62,Peru,13490
491,elizabeth72,brandy74@example.net,Chase Thompson,Femenino,42,Senegal,83371
500,edelgadoh,encarna@gmail.com,Encarna Delgado,masculino,45,España,19200

7.	Obtener el username de todos los usuarios cuyo país sea Alemania, Finlandia o Canadá

In [54]:

filtro = (df["country"] == "Finland") | (df["country"] == "Germany") | (df["country"] == "Canada")

df[filtro]["name"]

10           Sarah Combs
86          Jessica Mann
100            Ann Silva
132        Sharon Hodges
137       Collin Wallace
336         Julia Thomas
378          John Foster
387    Kristina Martinez
435        Michael Walsh
Name: name, dtype: object

8.	Obtener el nombre y correo electronico de todos los usuarios de sexo Femenino que sean del país Alemania

In [56]:
consulta = (df["gender"] == "Femenino") & (df["country"] == "Germany")

df[consulta][["name","email"]]

            name               email
86  Jessica Mann  chad22@example.org

9.	Obtener el promedio de edad de todos los usuarios de sexo Femenino de Canadá mayores de 20 años

In [62]:
filtro = (df["gender"] == "Femenino") & (df["country"] == "Canada") & (df["age"] > 20)
edades = df[filtro]["age"]
promedio = edades.mean()
print(promedio)

nan

10.	Conocer la cantidad de usuarios que residen en Finlandia.

In [69]:
filtro = df["country"] == "Finland" 

print(df[filtro]["username"].count())

4

11.	Explora la función “groupby” y muestra en consola la cantidad de hombres y mujeres en el dataframe

In [76]:
consulta = df[df[["gender"] == "Femenino"]]
mujeres = df.groupby("gender").size()

print(mujeres)

consulta = df[df[["gender"] == "Masculino"]]
hombres = df.groupby("gender").size()

print(hombres)

KeyError: False